hosts:
  - devices: 10.209.1.1 
    username : abc
    passwd: pqr
tests:
  - /home/ansible/Automation/Ansible/jsnapy_module_tests/jsnapy_tests/show_interface_descriptions.yml 
  - /home/ansible/Automation/Ansible/jsnapy_module_tests/jsnapy_tests/show_gbp_summary.yml
